name: Python package

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        pip install requirements.txt
    - name: Run tests and collect coverage
      run: |
        pytest api/test.py --cov --cov-reporter xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v2
      with:
        token: 932af2e3-86b7-48dd-b617-53040c432f57
